# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set SHAs for Nx Cloud
        uses: nrwl/nx-set-shas@v3

      - name: Run Nx commands
        run: pnpm exec nx affected -t build,test --parallel=3 --configuration=ci

      - name: Upload Nx Cloud Results
        run: pnpm exec nx-cloud upload --verbose
