name: Nx Cloud CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: Build and Test Affected
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Enable Corepack (optional but good)
        run: corepack enable

      - name: Set SHAs for Nx Cloud
        uses: nrwl/nx-set-shas@v3

      - name: Run format check, lint, test, build and record to Nx Cloud
        run: npx nx-cloud record -- npx nx format:check && npx nx affected -t lint test build e2e-ci
