name: CI/CD for mhc sites

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  dev-pr-check:
    name: PR Build & Lint (Dev)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: development
    env:
     NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Lint all apps
        run: pnpm nx lint mhc madhare

      - name: Test all apps
        run: pnpm nx test mhc madhare

      - name: Build all apps
        run: pnpm nx run-many --target=build --projects=mhc,madhare --configuration=production


  prod-deploy:
    name: Deploy Angular Sites
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    env:
     NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Build sites
        run: pnpm nx run-many --target=build --projects=mhc,madhare --configuration=production

      - name: Deploy sites to VM
        run: |
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          trap 'rm -f key.pem' EXIT
          scp -i key.pem -o StrictHostKeyChecking=no -r dist/apps/mhc/browser/* ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }}:/var/www/html/djps/
          scp -i key.pem -o StrictHostKeyChecking=no -r dist/apps/madhare/browser/* ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }}:/var/www/html/madhare/
