name: CI/CD for mhc sites

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  dev-pr-check:
    name: PR Build & Lint (Dev)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint all apps
        run: pnpm nx lint site-a site-b

      - name: Test all apps
        run: pnpm nx test site-a site-b

      - name: Build all apps
        run: pnpm nx run-many --target=build --projects=site-a,site-b --configuration=production


  prod-deploy:
    name: Deploy Angular Sites
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build sites
        run: pnpm nx run-many --target=build --projects=mhc --configuration=production

      - name: Deploy djps to VM
        run: |
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no -r dist/apps/mhc/browser/* ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }}:/var/www/djps/
